name: "Run Stale Check"

on:
  schedule:
    - cron: '0 0 * * *' # 每天凌晨自动运行一次
  workflow_dispatch:   

jobs:
  call-stale-logic:
    permissions:
      issues: write
      pull-requests: write
    uses: Foolllll-J/.github-shared-config/.github/workflows/stale-logic.yml@main